[tool.poetry]
name = "fast-api-starter-template"
version = "0.1.0"
description = "Project FastAPI template with some configurations already made and authentication implemented, to be used as a basis for other projects"
authors = ["Juliana Marques <julianabmarques@live.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.139.0"
uvicorn = "^0.51.0"
alembic = "^1.18.5"
psycopg = "^3.3.4"
sqlmodel = "^0.0.39"
pydantic-settings = "^2.14.2"
bcrypt = "^5.0.0"
email-validator = "^2.3.0"
pyjwt = "^2.13.0"
python-multipart = "^0.0.32"
pandas = "^3.0.3"
poetry-core = "^2.4.1"

[tool.poetry.group.dev.dependencies]
pylint = "^4.0.6"
flake8 = "^7.3.0"
pytest = "^9.1.1"
httpx = "^0.28.1"

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
